### ISSUE TITLE
Delete dashboard functionality

### ISSUE THREAD

**Issue by larsmathisen** [kundestyrt-norbit/mose-frontend#95]

**Comment by haakonnese** [comment]
Is this deleting of a dashboard as a whole or sensors from a dashboard. I have added functionality of deleting and adding sensors to a dashboard in #93, and created issue #107 for that

**Comment by larsmathisen** [comment]
This is deleting the dashboard itself. We'll need something on the frontend to delete them from the navbar list, and possible from the dashboard itself, though we only _need_ the former.
